version: "3"
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=tech_blog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  app:
    image: tajalislam/tech-forum
    command: npm start
    ports:
      - "3001:3001"
    depends_on:
      - db

  tech_forum_frontend:
    stdin_open: true
    build: .
    command: npm start
    volumes:
      - .:/app/frontend
      - ./node_modules:/app/frontend/node_modules
    ports:
      - 3000:3000